// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Test, Vm} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {HTLC} from "../src/HTLC.sol";

/// @title HtlcOracleTest
/// @notice Cross-package consistency oracle. Reads the JSON fixture generated by
///         `packages/state-machine/src/oracle.test.ts` (committed to the repo
///         under `packages/state-machine/test/fixtures/oracle.json`) and asserts
///         that `HTLC.rootOf`, `HTLC.hashLock`, and `HTLC.verifyPreimage`
///         match the off-chain `htlcMerkleRoot` / `htlcLeaf` / sha256 outputs
///         byte-for-byte. This is the linchpin between the TS state machine and
///         the Solidity adjudicator.
contract HtlcOracleTest is Test {
    using stdJson for string;

    string internal constant FIXTURE_PATH = "../state-machine/test/fixtures/oracle.json";
    uint256 internal constant RECORD_COUNT = 50;

    string internal json;

    function setUp() public {
        json = vm.readFile(FIXTURE_PATH);
        require(bytes(json).length > 0, "empty oracle fixture");
    }

    function test_fixtureMetadata_matches() public view {
        assertEq(json.readUint(".version"), 1);
        assertEq(json.readUint(".chainId"), 167009);
    }

    /// @dev We split the parity sweep across small forge tests so each chunk
    ///      runs in a fresh EVM memory frame. parseJson cheatcodes allocate
    ///      heavily and a single 50-record loop hits MemoryOOG.
    function test_oracle_parity_chunk_00_04() public view {
        _checkRange(0, 5);
    }

    function test_oracle_parity_chunk_05_09() public view {
        _checkRange(5, 10);
    }

    function test_oracle_parity_chunk_10_14() public view {
        _checkRange(10, 15);
    }

    function test_oracle_parity_chunk_15_19() public view {
        _checkRange(15, 20);
    }

    function test_oracle_parity_chunk_20_24() public view {
        _checkRange(20, 25);
    }

    function test_oracle_parity_chunk_25_29() public view {
        _checkRange(25, 30);
    }

    function test_oracle_parity_chunk_30_34() public view {
        _checkRange(30, 35);
    }

    function test_oracle_parity_chunk_35_39() public view {
        _checkRange(35, 40);
    }

    function test_oracle_parity_chunk_40_44() public view {
        _checkRange(40, 45);
    }

    function test_oracle_parity_chunk_45_49() public view {
        _checkRange(45, 50);
    }

    function _checkRange(uint256 from, uint256 toExclusive) internal view {
        for (uint256 i = from; i < toExclusive; i++) {
            _checkRecord(i);
        }
    }

    function _checkRecord(uint256 i) internal view {
        string memory base = string.concat(".records[", vm.toString(i), "]");
        bytes32 expectedRoot = json.readBytes32(string.concat(base, ".htlcsRoot"));

        bytes32[] memory expectedLeaves = json.readBytes32Array(string.concat(base, ".leafHashes"));
        uint256 n = expectedLeaves.length;
        if (n == 0) {
            HTLC.Lock[] memory empty = new HTLC.Lock[](0);
            assertEq(HTLC.rootOf(empty), expectedRoot, "empty root must be bytes32(0)");
            return;
        }

        HTLC.Lock[] memory locks = new HTLC.Lock[](n);
        for (uint256 j = 0; j < n; j++) {
            string memory entry = string.concat(base, ".htlcs[", vm.toString(j), "]");
            string memory direction = json.readString(string.concat(entry, ".direction"));
            locks[j] = HTLC.Lock({
                id: json.readBytes32(string.concat(entry, ".id")),
                amount: vm.parseUint(json.readString(string.concat(entry, ".amount"))),
                paymentHash: json.readBytes32(string.concat(entry, ".paymentHash")),
                expiry: uint64(vm.parseUint(json.readString(string.concat(entry, ".expirySec")))),
                direction: keccak256(bytes(direction)) == keccak256("AtoB") ? 0 : 1
            });
        }

        HTLC.Lock[] memory sorted = _sortById(locks);
        for (uint256 j = 0; j < n; j++) {
            assertEq(HTLC.hashLock(sorted[j]), expectedLeaves[j], "leaf parity");
        }

        assertEq(HTLC.rootOf(locks), expectedRoot, "root parity");

        for (uint256 j = 0; j < n; j++) {
            string memory pre = string.concat(base, ".preimages[", vm.toString(j), "]");
            bytes32 paymentHash = json.readBytes32(string.concat(pre, ".paymentHash"));
            bytes32 preimageWord = json.readBytes32(string.concat(pre, ".preimage"));
            assertTrue(this._verifyPreimage(paymentHash, abi.encodePacked(preimageWord)), "verifyPreimage parity");
        }
    }

    function _verifyPreimage(bytes32 paymentHash, bytes calldata preimage) external pure returns (bool) {
        return HTLC.verifyPreimage(paymentHash, preimage);
    }

    function _sortById(HTLC.Lock[] memory locks) internal pure returns (HTLC.Lock[] memory) {
        uint256 n = locks.length;
        HTLC.Lock[] memory out = new HTLC.Lock[](n);
        for (uint256 i = 0; i < n; i++) {
            out[i] = locks[i];
        }
        for (uint256 i = 1; i < n; i++) {
            HTLC.Lock memory key = out[i];
            uint256 j = i;
            while (j > 0 && out[j - 1].id > key.id) {
                out[j] = out[j - 1];
                unchecked {
                    j--;
                }
            }
            out[j] = key;
        }
        return out;
    }
}
