#!/usr/bin/env bash
# Assemble docs/mainnet-e2e-test-log.md from the artifacts captured during
# phases 00–04. Operator should still hand-edit for narrative + Taikoscan
# links; this script provides the skeleton populated with the captured data.
#
# Usage:
#   scripts/mainnet-smoke/05-finalize.sh [--out docs/mainnet-e2e-test-log.md]

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$HERE/lib/common.sh"

OUT="docs/mainnet-e2e-test-log.md"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --out) OUT="$2"; shift 2 ;;
    -h|--help) sed -n '/^# Usage/,/^$/p' "$0" | sed 's/^# \{0,1\}//'; exit 2 ;;
    *) fail "unknown arg: $1" ;;
  esac
done

LOG_DIR="$(resolve_log_dir)"
[[ -d "$LOG_DIR" ]] || fail "log dir not found: $LOG_DIR"

slurp() {
  local f="$LOG_DIR/$1"
  [[ -f "$f" ]] && cat "$f" || echo '{}'
}

cat > "$OUT" <<EOF
# Mainnet E2E test log

> Generated by \`scripts/mainnet-smoke/05-finalize.sh\` on $(date -u +'%Y-%m-%dT%H:%M:%SZ').
> Source artifacts: \`$LOG_DIR\`.

## Pre-check

\`\`\`json
$(slurp precheck.json)
\`\`\`

## Hub health snapshot

\`\`\`json
$(slurp hub-health.json)
\`\`\`

## Channels opened

\`\`\`json
$(slurp channels.json)
\`\`\`

## Payment

\`\`\`json
$(slurp pay.json)
\`\`\`

## Cooperative close

\`\`\`json
$(slurp close.json)
\`\`\`

## Dispute drill (Carol)

\`\`\`json
$(slurp dispute.json)
\`\`\`

## Operator narrative

_Add Taikoscan links for every tx hash, observed wall-clock timings, and
any incident notes here. Sign off below when complete._

| Sign-off | Date | Operator |
|---|---|---|
|  |  |  |
EOF

green "Wrote $OUT"
EOF
